### ISSUE TITLE
Screenshot of font-style change - line 4

### ISSUE THREAD

**Issue by jenniferparmar** [Hack-The-Tunnels-8/hack-the-tunnels-glasses-gals#1]
<img width="483" alt="Screenshot 2023-09-30 121800" src="https://github.com/Hack-The-Tunnels-8/hack-the-tunnels-glasses-gals/assets/146406069/7fc8b7e9-cb82-4bbb-9171-66b5ffb17d4f">

- screenshot for font-style issue, line 4

**Comment by jenniferparmar** [comment]
!review

**Comment by MVillagomez56** [comment]
!approve

**Comment by MVillagomez56** [comment]
Please resubmit this in the appropriate issue.
